
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Linux - 6.1.66-060166-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "cmake/cmake-d/cmake-d/CMakeDetermineDCompiler.cmake:136 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the D compiler identification source file "CMakeDCompilerId.d" failed.
      Compiler: CMAKE_D_COMPILER-NOTFOUND 
      Build flags: 
      Id flags:  
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "cmake/cmake-d/cmake-d/CMakeDetermineDCompiler.cmake:136 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the D compiler identification source file "CMakeDCompilerId.d" failed.
      Compiler: CMAKE_D_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -c 
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "cmake/cmake-d/cmake-d/CMakeDetermineDCompiler.cmake:136 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the D compiler identification source file "CMakeDCompilerId.d" failed.
      Compiler: CMAKE_D_COMPILER-NOTFOUND 
      Build flags: 
      Id flags:  
      
      The output was:
      no such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/linuxbrew/.linuxbrew/Cellar/cmake/3.28.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "cmake/cmake-d/cmake-d/CMakeDetermineDCompiler.cmake:136 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the D compiler identification source file "CMakeDCompilerId.d" failed.
      Compiler: CMAKE_D_COMPILER-NOTFOUND 
      Build flags: 
      Id flags: -c 
      
      The output was:
      no such file or directory
      
      
...
